-- MySQL Script generated by MySQL Workbench
-- Thu May 18 20:59:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET PASSWORD FOR root@localhost='';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Library_Member`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Library_Member` (
  `Member_ID` INT NOT NULL AUTO_INCREMENT,
  `Member_Name` VARCHAR(100) NOT NULL,
  `Member_Phone_Number` INT NULL,
  `Member_Email` VARCHAR(100) NULL,
  `Membership_Status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Member_ID`),
  UNIQUE INDEX `Member_ID_UNIQUE` (`Member_ID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Library_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Library_Staff` (
  `Staff_ID` INT NOT NULL AUTO_INCREMENT,
  `Staff_Name` VARCHAR(100) NOT NULL,
  `Staff_Phone_Number` INT NULL,
  `Staff_Email` VARCHAR(100) NULL,
  `Position` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Staff_ID`),
  UNIQUE INDEX `Member_ID_UNIQUE` (`Staff_ID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` INT NOT NULL AUTO_INCREMENT,
  `Book_Title` VARCHAR(100) NOT NULL,
  `Book_Author` VARCHAR(100) NOT NULL,
  `Book_Publication_Year` VARCHAR(100) NOT NULL,
  `Book_Availability` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `Member_ID_UNIQUE` (`ISBN` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;